server:
  port: 8080

  # Configuración de Jackson (JSON)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Bogota

# Configuración personalizada para la aplicación
app:
  name: Sistema de Gestión de Pedidos
  version: 1.0.0
  description: Backend para gestión de pedidos con Spring Boot

spring:
  application:
    name: pedidos-backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.pedidos.backend: WARN
    root: WARN
    org.hibernate.SQL: WARN