pipeline {
    agent any

    environment {
        GIT_COMMIT_SHORT = GIT_COMMIT.take(7)
    }

    triggers {
        githubPush()
    }
    stages {
        stage('Helm version') {
            steps {
                sh 'helm version'
            }
        }
        stage('Checkout') {
            steps {
                git url: 'https://github.com/alejandrazuleta1/k8s', branch: 'main'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('pedidos-backend') {
                    script {
                        sh 'docker build -t alezuleta/my-tech:${GIT_COMMIT_SHORT} .'
                    }
                }
            }
        }
        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials',
                                             usernameVariable: 'USER',
                                             passwordVariable: 'PASS')]) {
                    sh 'docker login -u $USER -p $PASS'
                    sh 'docker push alezuleta/my-tech:${GIT_COMMIT_SHORT}'
                }
            }
        }
        stage('Update Helm Values') {
            steps {
                script {
                    sh """
                        cd charts
                        sed -i 's/tag: .*/tag: ${GIT_COMMIT_SHORT}/' pedido-app/values.yaml
                        helm package pedido-app/.
                        ls -l
                        cd ..
                    """
                }
            }
        }
        stage('Checkout repo charts') {
            steps {
                dir('pedidos-charts') {
                    git url: 'https://github.com/alejandrazuleta1/pedidos-charts', branch: 'main'
                    script {
                        sh """
                            ls -l
                            rm charts/pedido-app-0.1.0.tgz
                            cp /var/jenkins_home/workspace/unisabana/charts/pedido-app-0.1.0.tgz charts
                            git add .
                            git commit -m "Cambio version"
                            git push
                        """
                    }
                }
            }
        }
    }
}