pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/alejandrazuleta1/k8s', branch: 'main'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t alezuleta/my-tech:latest .'
            }
        }
        stage('Push to Registry') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-credentials', variable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u alezuleta --password-stdin'
                    sh 'docker push alezuleta/my-tech:latest'
                }
            }
        }
    }
}
